keys:
  - &lifbrasir age13ygw3n6x7hph9q5e6zhwwcel32r2lg2ut93ssuj4r79jddx6yspsnrzjvs
  - &oq age1akdvdtgd835g84xgyjz377wyw93azvglvggl5aas62z50xpcpatscc58a6
creation_rules:
  - path_regex: ^users/oq/.*secrets.*$
    key_groups:
      - age:
          - *oq
  - path_regex: secrets.*$
    key_groups:
      - age:
          - *lifbrasir
          - *oq
