# `.wslconfig` is read by the WSL host service on Windows, not by this NixOS
# system: it lives at %UserProfile%\.wslconfig, outside of any distro, and
# configures the VM that every WSL 2 distro shares.
#
# It is kept here anyway because every value in it is a decision about this
# specific machine -- 32 GB of RAM shared with a Windows desktop, 8 logical
# CPUs, and a nix store on the NVMe at C:\wsl\distros\nixos -- and a copy that
# exists only on the Windows filesystem has nothing keeping it honest.
# Activation writes it back out, so this file stays the source of truth rather
# than a stale transcript of one.
#
# None of it takes effect until the VM is restarted with `wsl --shutdown`,
# which cannot be run from inside the VM that is being shut down.
{
  lib,
  pkgs,
  ...
}:
with lib; let
  # The Windows user profile, reached through the DrvFs automount.
  profile = "/mnt/c/Users/User";

  wslconfig = pkgs.writeText "wslconfig" ''
    # Generated by NixOS from hosts/loki.lif/wslconfig.nix -- edit it there,
    # not here. Rewritten on every `nixos-rebuild switch`.

    [wsl2]

    # Left at the host default of 50% (~16 GB of 32). 20 GB was tried here and
    # reverted: paired with the `gradual` reclaim mode this file used to set,
    # the VM grew its page cache until Windows itself was under 2 GB free and
    # began killing processes. The reclaim mode has since gone back to the
    # default, but the ceiling stays -- 32 GB shared with a Windows desktop
    # has no room for a larger one.
    memory=16GB

    # All 8 logical processors. Already the default; pinned so that a change
    # to the host's core count is a visible edit here rather than a silent
    # change in behaviour.
    processors=8

    # Default would be 25% of VM memory. The swap VHD lives at %Temp%\swap.vhdx
    # on C:, which is the NVMe SSD -- the right disk for it.
    swap=8GB

    # Default is 60s of idle before the VM is torn down. This distro is not
    # interactive-only: docker, odoo and kimai run in it as services, and WSL
    # counts "idle" as no client being attached, not as nothing running. Hold
    # the VM up for an hour so those survive the gaps between shells.
    vmIdleTimeout=3600000

    [general]

    # The same concern one level down, and the sharper one: the default tears a
    # distro down after 15s of idle. -1 disables that outright, which is what
    # actually keeps the services above alive.
    #
    # The cost is that nothing then releases the VHDX on its own. Moving,
    # compacting or otherwise touching the disk from Windows needs an explicit
    # `wsl --shutdown` first -- and note that shuts down every distro, since
    # WSL 2 runs them all in one shared VM.
    instanceIdleTimeout=-1

    [experimental]

    # Back to the WSL default. `gradual` was set here while the store still
    # lived on a 7200rpm disk, where holding on to the page cache was what hid
    # the seek latency -- and it is also what let the VM starve the host down
    # to 2 GB free. The store now sits on the NVMe, so that cache is worth far
    # less than the headroom, and `dropCache` hands it back to Windows at once.
    autoMemoryReclaim=dropCache

    # sparseVhd is deliberately NOT enabled. Microsoft gated sparse VHDs behind
    # an --allow-unsafe flag in WSL 2.5.6 after reports of ext4 corruption, and
    # as of 2.7.3 the root cause was still never published. Setting it here
    # force-enables that same unsafe path for any newly created VHD.
    #
    # It would also be self-defeating: `diskpart compact vdisk` refuses sparse
    # files outright ("must not be sparse"), so turning this on trades the one
    # reclaim method that works on Windows Home for one that risks the store.
    # To shrink a disk, shut WSL down and compact it with diskpart instead.
  '';
in {
  # Written on activation rather than symlinked: the WSL host service reads
  # this path before any distro is running, so it cannot be a link into a nix
  # store that is not mounted yet.
  system.activationScripts.wslconfig.text = ''
    # /mnt/c only exists once automount has run. A file that belongs to the
    # Windows side is not worth failing an activation over, so skip quietly.
    if [ -d "${profile}" ]; then
      if ! ${pkgs.diffutils}/bin/cmp -s ${wslconfig} "${profile}/.wslconfig"; then
        ${pkgs.coreutils}/bin/cp ${wslconfig} "${profile}/.wslconfig"
        echo "wslconfig: updated ${profile}/.wslconfig -- run 'wsl --shutdown' from Windows to apply it"
      fi
    else
      echo "wslconfig: ${profile} is not mounted, skipping"
    fi
  '';
}
