{inputs, ...}:
with inputs.nixpkgs.lib; {
  flake.nixosModules.wsl = {
    config,
    pkgs,
    ...
  }: let
    cfg = config.modules.wsl;

    wslconfig = pkgs.writeText "wslconfig" ''
      # Generated by NixOS from this host's wslconfig.nix -- edit it there, not
      # here. Rewritten on every `nixos-rebuild switch`.

      ${cfg.wslconfig.text}
    '';
  in {
    imports = [
      inputs.nixos-wsl.nixosModules.default
    ];

    options.modules.wsl = {
      enable = mkEnableOption "wsl";
      defaultUser = mkOption {
        type = types.nullOr types.str;
        description = "The default user for the wsl sytem to use.";
        default = null;
      };

      wslconfig = {
        text = mkOption {
          type = types.nullOr types.lines;
          default = null;
          description = ''
            Contents of `%UserProfile%\.wslconfig` on the Windows host.

            This configures the single VM that every WSL 2 distro shares, so it
            is a statement about the machine rather than about this system --
            which is why it is per-host rather than set here. Null leaves
            whatever is on the Windows side alone.

            None of it takes effect until the VM is restarted with
            `wsl --shutdown`, which cannot be run from inside the VM being
            shut down.
          '';
        };

        windowsProfile = mkOption {
          type = types.str;
          default = "/mnt/c/Users/User";
          description = ''
            The Windows user profile directory, reached through the DrvFs
            automount. `.wslconfig` is written into it.
          '';
        };
      };
    };

    config = mkIf cfg.enable {
      wsl = {
        enable = true;
        defaultUser = mkIf (cfg.defaultUser != null) cfg.defaultUser;
        interop.register = true;
      };

      # Written on activation rather than symlinked: the WSL host service reads
      # this path before any distro is running, so it cannot be a link into a
      # nix store that is not mounted yet.
      system.activationScripts = mkIf (cfg.wslconfig.text != null) {
        wslconfig.text = let
          profile = cfg.wslconfig.windowsProfile;
        in ''
          # /mnt/c only exists once automount has run. A file that belongs to
          # the Windows side is not worth failing an activation over, so skip
          # quietly.
          if [ -d "${profile}" ]; then
            if ! ${pkgs.diffutils}/bin/cmp -s ${wslconfig} "${profile}/.wslconfig"; then
              ${pkgs.coreutils}/bin/cp ${wslconfig} "${profile}/.wslconfig"
              echo "wslconfig: updated ${profile}/.wslconfig -- run 'wsl --shutdown' from Windows to apply it"
            fi
          else
            echo "wslconfig: ${profile} is not mounted, skipping"
          fi
        '';
      };
    };
  };
}
