{...}: {
  home-manager.users.oq = {...}: {
    imports = [
      ./home._common.nix
      ../../modules/browsers/firefox/firefox.nix
      ../../modules/browsers/firefox/zen.nix
      ../../modules/browsers/firefox/tor.nix
      ../../modules/browsers/chrome/chrome.nix
      ../../modules/browsers/chrome/work.nix
      ../../modules/citrix
      ../../modules/cursors
      ../../modules/discord
      ../../modules/fonts
      ../../modules/hypr
      ../../modules/kitty
      ../../modules/nextcloud
      ../../modules/obsidian
      ../../modules/rofi
      ../../modules/secrets
      ../../modules/todoist
      ../../modules/youtube-music
      ../../modules/postman
      ../../modules/starship
      ../../modules/theme
      ../../modules/vscode
      ../../modules/repos
      ../../modules/splatmoji
      ../../modules/teams
      ../../modules/wallpaper-engine
      ../../modules/rider
      ../../modules/kooha
      ../../modules/shotcut
      ../../modules/zathura
      ../../modules/xdg-utils
      ../../modules/minecraft/prismlauncher.nix
      ../../modules/libreoffice
      ../../modules/zoom
    ];
  };
}
