github.com:
    git_protocol: ENC[AES256_GCM,data:NwT4oJU=,iv:JEd5HEMt4SoiCYy5seOOTdNX+WGjoWfoxWiRyDJa9Zg=,tag:FkCq/+TJF+x6B5BinSl4Pg==,type:str]
    users:
        0qln:
            oauth_token: ENC[AES256_GCM,data:huBmkD07hk2NQwv0/MGndU1MLcdPXOKKEpV8OYP8HM5IDFSZwYeXQA==,iv:tZkTyZEcOrddLzqTqh++QDNtQbEaYMpNqrskCEMwwT0=,tag:ZJT9QHjMhnjLLI/P9pvmrg==,type:str]
    user: ENC[AES256_GCM,data:MCnaCQ==,iv:dVkV7EeuPXkqdyoJQSwW9a1wXWn6g5cyUtnHTBwAT80=,tag:XIFQ/fpXY6RD4U1GvFS00A==,type:str]
    oauth_token: ENC[AES256_GCM,data:EoL3T+y/8cmmzuE6Ul5PgyUlGfoiYPRoWXoq0T5Iw87HX2li5SQa8w==,iv:M16Zj27frdoHECGK2PuMLkKj/oW19g4nqyFp9FYGQ6A=,tag:d2QFr1t4W+Vo/qwFs36oWg==,type:str]
sops:
    age:
        - recipient: age1akdvdtgd835g84xgyjz377wyw93azvglvggl5aas62z50xpcpatscc58a6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNDJGMk9UK3pOUVQ1V1FR
            VGI1L20xUmF2U2JWb2V5Z1AreEQyMDNSY3pRCmQxdkhXa1BXdWV3cWhMeXNJMEdj
            QlFIRGdDTjAzYWZGT1hKVXhlT1VQRGMKLS0tIEl6a1VMMHJ3R2VIZkVtcjFJUU1X
            eVJZdVhyNEVlNUROSXJINTFlSHp5V00K24p18GPJJEFuC1y964ZkaJjyuEz2PYs1
            vwiNad9R1WdYrjrcs7JvkJ4rrlOS9Mw0eqsUzScKS62fpRWi4ptwNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-24T12:15:46Z"
    mac: ENC[AES256_GCM,data:DwAuX9tX3v7kCPdeb8Xx3LjV1elS7abAeZOk+ur9Lx2PCIHi2dtB51U+2+lbLbxzaz9YyhhX4eEucDM5V4Cb2TJ5hmqpwkr2I7+JSOyMe+jBx7MwLb8EC8RkH5VhVSRBapfjFqDTQOXQ/AemX5dUDOvpJfgoLkFjFEzhH1hL1l0=,iv:8Tc2YZGDTmcbV0lUBl/3NPUITgl3LC73ZwxyApafUXg=,tag:ffDWzXYK31Q+BeQLJIkYfQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
