github.com:
    git_protocol: ENC[AES256_GCM,data:NwT4oJU=,iv:JEd5HEMt4SoiCYy5seOOTdNX+WGjoWfoxWiRyDJa9Zg=,tag:FkCq/+TJF+x6B5BinSl4Pg==,type:str]
    users:
        0qln:
            oauth_token: ENC[AES256_GCM,data:huBmkD07hk2NQwv0/MGndU1MLcdPXOKKEpV8OYP8HM5IDFSZwYeXQA==,iv:tZkTyZEcOrddLzqTqh++QDNtQbEaYMpNqrskCEMwwT0=,tag:ZJT9QHjMhnjLLI/P9pvmrg==,type:str]
    user: ENC[AES256_GCM,data:MCnaCQ==,iv:dVkV7EeuPXkqdyoJQSwW9a1wXWn6g5cyUtnHTBwAT80=,tag:XIFQ/fpXY6RD4U1GvFS00A==,type:str]
    oauth_token: ENC[AES256_GCM,data:EoL3T+y/8cmmzuE6Ul5PgyUlGfoiYPRoWXoq0T5Iw87HX2li5SQa8w==,iv:M16Zj27frdoHECGK2PuMLkKj/oW19g4nqyFp9FYGQ6A=,tag:d2QFr1t4W+Vo/qwFs36oWg==,type:str]
sops:
    age:
        - recipient: age1akdvdtgd835g84xgyjz377wyw93azvglvggl5aas62z50xpcpatscc58a6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNzFsYndKQWhLNFNLMmtq
            ZFAwdFlBdCtOdkdQMnkwOHcrZDZaSUo2cG1JCk9rSkVmMll3MHkrblpFTHZLczJL
            YkVzSmFCSkM0Sm8vbTV1dUhHRzcybGcKLS0tIEg2TjJkZ1g2ZUtKUmpBM1BxeklN
            YXR6RHZFbVc0OWNIZ2VUM3ZxMEVEb0EK4tiANCEML+EwgN7l5Cq+FW+cNO/ea0nQ
            84Bs4fC7Diptf5ayfgaN5QSRMLJFUmOYJYcUXMj/CAD4qBhvryWadw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qtk6ap8wyjw9qvt4xe6uze0ucp63nqefpqhel6rl2uv7kp6ddmsz5ujkuvq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHlnc3BQUSBBcHh0U3ZW
            bUVHQm1pQmRmbksyMnd6NjI1YWN5S0FNbEY5NTY3YkVLcHpwOApXaWtMUTdmcHlO
            eWZFTmgveVhFU0dtaWpBWTdtS1ZROXkrTkFXNFJ1OGp3Ci0tLSBLZHBPRzFZTzEr
            NnpxWmxHQVNvSmlneEdUTG0rZmNNT3lIeWU3MFRXSUxrCnByqBN07d3Sqb3gQBaz
            jbdde1SyOad7x2DWds6HSwTMqODeu1WSCoVBPsGZmc46+oWEhLqvhsTuaX0p0PSJ
            rZU=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qtqwt6yyn894y7xlqgx33ljlmqawkz59dcrthqj8tt5hkpx5gy3v5aqf8wd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGRESzNiZyBBcitFbFVw
            WlB6WmJXUmZvNXhRekw2dFJQUi83ZkFsZStqWXFsN0I3cThuNQp3SHJtVW5zT21D
            WUVGdUhNUnB3eTl0SWdsSy9HZi84dkdaMmJMSWFwNUFRCi0tLSBld0hOb0ltaFQ5
            U0NyTHZoekZsY2VPZzBWcy9PVTA5ZGR4K3d3cDhKMVpZCn9ycBVLXTZe5odcjxwW
            0K1UcGWIICegrav1T+aDTGDuitSKYf6QwRXGmey2SODzvVuuM7F2goRiU1nRTS7A
            QJQ=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-24T12:15:46Z"
    mac: ENC[AES256_GCM,data:DwAuX9tX3v7kCPdeb8Xx3LjV1elS7abAeZOk+ur9Lx2PCIHi2dtB51U+2+lbLbxzaz9YyhhX4eEucDM5V4Cb2TJ5hmqpwkr2I7+JSOyMe+jBx7MwLb8EC8RkH5VhVSRBapfjFqDTQOXQ/AemX5dUDOvpJfgoLkFjFEzhH1hL1l0=,iv:8Tc2YZGDTmcbV0lUBl/3NPUITgl3LC73ZwxyApafUXg=,tag:ffDWzXYK31Q+BeQLJIkYfQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
