github.com:
    git_protocol: ENC[AES256_GCM,data:NwT4oJU=,iv:JEd5HEMt4SoiCYy5seOOTdNX+WGjoWfoxWiRyDJa9Zg=,tag:FkCq/+TJF+x6B5BinSl4Pg==,type:str]
    users:
        0qln:
            oauth_token: ENC[AES256_GCM,data:huBmkD07hk2NQwv0/MGndU1MLcdPXOKKEpV8OYP8HM5IDFSZwYeXQA==,iv:tZkTyZEcOrddLzqTqh++QDNtQbEaYMpNqrskCEMwwT0=,tag:ZJT9QHjMhnjLLI/P9pvmrg==,type:str]
    user: ENC[AES256_GCM,data:MCnaCQ==,iv:dVkV7EeuPXkqdyoJQSwW9a1wXWn6g5cyUtnHTBwAT80=,tag:XIFQ/fpXY6RD4U1GvFS00A==,type:str]
    oauth_token: ENC[AES256_GCM,data:EoL3T+y/8cmmzuE6Ul5PgyUlGfoiYPRoWXoq0T5Iw87HX2li5SQa8w==,iv:M16Zj27frdoHECGK2PuMLkKj/oW19g4nqyFp9FYGQ6A=,tag:d2QFr1t4W+Vo/qwFs36oWg==,type:str]
sops:
    age:
        - recipient: age1akdvdtgd835g84xgyjz377wyw93azvglvggl5aas62z50xpcpatscc58a6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzY1k0WE9MUXNLOFJsSG1x
            WExKYTFsa21EU1VsRDRFWUwrM0lyT3J2YUY0CkxubGRyY0JzRUxDM2xpZEhsTSs0
            bFpiYnBFRTd4b2RlTTVaeWQ3c1lPb0EKLS0tIEtqRWI5S3ZreTJtTnZQZmYyVXQx
            YzBQVHRiRnArblgxeWp4L0ZsS0NqMHMKUJhqHml27XxzX8XEuC+A+Vhe4yaj4uXL
            PxG6yo5Gxtl+ANE2e2dAwu2bzjyJCjODhrN10Q16P21onhXc7UaofQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qtk6ap8wyjw9qvt4xe6uze0ucp63nqefpqhel6rl2uv7kp6ddmsz5ujkuvq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHlnc3BQUSBBOTBRdkdi
            eDhOMjFmU21LMXh2b05iV28rVDVFenN3eFpSMDhRaDJ4QW5WYwpDb2xFZXRIT3Jq
            NzE3MHVuN095dm1WaHVoalVCM0xIZDYwVWVtemhXMTdBCi0tLSBOTCs0RUVkK3lt
            QmkzaHJvcTc5NFlzTStlc0RKN29qcGMxRy9xWkppOGpJCp1Il3rIQDkiNud4mkBO
            80dbCD6R80V6u3I++LGw2CQpr9vkfKrglTLJQEEB8z3hqwF+PNssUlA9g4I1Io6n
            eaA=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qt6apkfjlfpun32ppk4zxrj9jh7dyrcfwr59trl2des3r7pmfxdu5jst7yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IC92UXJGQSBBdlJ2VWhT
            TzYySnhrZmFuamVpNVJkeXhEOEJ1Yi80ajJTU21KTkNrODhINgovYXdraFlpMVFq
            UE5tYkxpTXFqc0FPck5uZitxaGdRZERhWUVQdmtGaGRjCi0tLSBJUFp4U3ZNM2hw
            cmRiQ25uS2VZaGdwSVFTYVRFMjllRHh2RWIyenpLYnRNCmS+CGF/B5W+Mps39PWk
            zwhw6UEcfWoHkMy+4P4Ap7xMRIXHuKlLEJHOXDj3NfoL12F1ytwZFfhtUP6bThr2
            Phw=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-24T12:15:46Z"
    mac: ENC[AES256_GCM,data:DwAuX9tX3v7kCPdeb8Xx3LjV1elS7abAeZOk+ur9Lx2PCIHi2dtB51U+2+lbLbxzaz9YyhhX4eEucDM5V4Cb2TJ5hmqpwkr2I7+JSOyMe+jBx7MwLb8EC8RkH5VhVSRBapfjFqDTQOXQ/AemX5dUDOvpJfgoLkFjFEzhH1hL1l0=,iv:8Tc2YZGDTmcbV0lUBl/3NPUITgl3LC73ZwxyApafUXg=,tag:ffDWzXYK31Q+BeQLJIkYfQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
