$wallpaper = {{wallpaper}}
$background = rgb({{background | strip}})
$background_rgba = rgba({{background | strip}}BB)
$foreground = rgb({{foreground | strip}})
$foreground_raw = ##{{foreground | strip}}
$background_raw = ##{{background | strip}}
$color1 = rgb({{color1 | strip}})
$color3 = rgb({{color3 | strip}})
